CREATE TABLE users (
	id VARCHAR(50),
	pwd VARCHAR(50),
	teach TINYINT(1) UNSIGNED DEFAULT 0,
	f_name VARCHAR(50),
	l_name VARCHAR(50),
	r_one TINYINT(1) UNSIGNED DEFAULT 0,
	r_two TINYINT(1) UNSIGNED DEFAULT 0,
	r_three TINYINT(1) UNSIGNED DEFAULT 0);